# Generated by Django 5.1.7 on 2025-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cilindro',
            field=models.IntegerField(choices=[(5, '5 kg'), (11, '11 kg'), (15, '15 kg'), (45, '45 kg')]),
        ),
    ]
