# Generated by Django 5.1.7 on 2025-03-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_detallecompra_cilindro'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cilindro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cilindro'),
        ),
    ]
