# Generated by Django 5.1.7 on 2025-03-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_cilindro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
